Repository imdangg/imdang-android, pull requests merged in 2025-01, with the labels that each got.

#31 홈 무료 패스권 팝업, 툴팁 구현
  app/src/main/java/info/imdang/imdang/common/bindingadapter/RecyclerViewBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/common/util/DateTimeUtils.kt
  app/src/main/java/info/imdang/imdang/ui/main/MainActivity.kt
  app/src/main/java/info/imdang/imdang/ui/main/MainViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/HomeEvent.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/HomeFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/HomeViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/bottomsheet/HomeFreePassBottomSheet.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchFragment.kt
  app/src/main/res/layout/bottom_sheet_home_free_pass.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_search.xml
  component/src/main/res/drawable/ic_close.xml
  component/src/main/res/drawable/ic_free_pass.xml
  component/src/main/res/drawable/ic_polygon_up.xml
  component/src/main/res/drawable/selector_white_gray200_all8.xml
  component/src/main/res/drawable/sr_white_gray200_all8.xml
  component/src/main/res/values/strings.xml
  data/src/main/java/info/imdang/data/datasource/lcoal/HomeLocalDataSource.kt
  data/src/main/java/info/imdang/data/di/RepositoryModule.kt
  data/src/main/java/info/imdang/data/repository/HomeRepositoryImpl.kt
  domain/src/main/java/info/imdang/domain/repository/HomeRepository.kt
  domain/src/main/java/info/imdang/domain/usecase/home/GetCloseTimeOfHomeFreePassUseCase.kt
  domain/src/main/java/info/imdang/domain/usecase/home/SetCloseTimeOfHomeFreePassUseCase.kt
  local/src/main/java/info/imdang/local/constant/LocalConstant.kt
  local/src/main/java/info/imdang/local/datasource/HomeLocalDataSourceImpl.kt
  local/src/main/java/info/imdang/local/di/LocalDataSourceModule.kt
Labels: 리뷰 완료

#32 인사이트 상세 교환 팝업 구현
  app/src/main/java/info/imdang/imdang/base/BaseDialog.kt
  app/src/main/java/info/imdang/imdang/model/insight/InsightVo.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailActivity.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailEvent.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/insight/bottomsheet/MyInsightsBottomSheet.kt
  app/src/main/res/layout/bottom_sheet_my_insights.xml
  app/src/main/res/layout/dialog_exchange.xml
  app/src/main/res/layout/item_insight_detail_basic_info.xml
  app/src/main/res/layout/item_insight_detail_my_insight.xml
  component/src/main/res/drawable/ic_check_for_dialog.xml
  component/src/main/res/drawable/selector_white_gray100_all100.xml
  component/src/main/res/drawable/sr_white_all20.xml
  component/src/main/res/values/strings.xml
  component/src/main/res/values/text-styles.xml
Labels: 리뷰 완료

#35 지도 서비스 안내 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/map/SearchByMapActivity.kt
  app/src/main/java/info/imdang/imdang/ui/main/storage/StorageFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/storage/map/StorageByMapActivity.kt
  app/src/main/res/layout/activity_search_by_map.xml
  app/src/main/res/layout/activity_storage_by_map.xml
  app/src/main/res/layout/fragment_storage.xml
  component/src/main/res/values/strings.xml
Labels: 리뷰 완료

#38 마이페이지 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/info/imdang/imdang/common/ext/ContextExt.kt
  app/src/main/java/info/imdang/imdang/model/my/MyInfoVo.kt
  app/src/main/java/info/imdang/imdang/ui/common/CommonDialog.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailActivity.kt
  app/src/main/java/info/imdang/imdang/ui/login/LoginActivity.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/HomeEvent.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/HomeFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/HomeViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/my/MyActivity.kt
  app/src/main/java/info/imdang/imdang/ui/my/MyEvent.kt
  app/src/main/java/info/imdang/imdang/ui/my/MyViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/my/term/ServiceTermActivity.kt
  app/src/main/java/info/imdang/imdang/ui/my/withdraw/WithdrawActivity.kt
  app/src/main/java/info/imdang/imdang/ui/my/withdraw/WithdrawEvent.kt
  app/src/main/java/info/imdang/imdang/ui/my/withdraw/WithdrawViewModel.kt
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/activity_service_term.xml
  app/src/main/res/layout/activity_withdraw.xml
  app/src/main/res/layout/dialog_common.xml
  component/src/main/res/drawable/ic_check_gray.xml
  component/src/main/res/drawable/ic_logout.xml
  component/src/main/res/drawable/ic_right.xml
  component/src/main/res/drawable/ic_sign_for_dialog.xml
  component/src/main/res/drawable/selector_white_cbd5e0_all8.xml
  component/src/main/res/drawable/selector_white_gray100_all6.xml
  component/src/main/res/values/strings.xml
Labels: 리뷰 완료

#39 Github Actions, fastlane 연동
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
  .gitignore
  Gemfile
  Gemfile.lock
  app/build.gradle.kts
  app/src/main/java/info/imdang/imdang/ui/login/LoginActivity.kt
  domain/build.gradle.kts
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
  remote/build.gradle.kts
Labels: 리뷰 완료

#45 온보딩 화면 UI 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/info/imdang/imdang/ui/login/LoginActivity.kt
  app/src/main/java/info/imdang/imdang/ui/login/LoginEvent.kt
  app/src/main/java/info/imdang/imdang/ui/login/LoginViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/login/bottomsheet/OnboardingBottomSheet.kt
  app/src/main/java/info/imdang/imdang/ui/login/onboarding/OnboardingActivity.kt
  app/src/main/java/info/imdang/imdang/ui/login/onboarding/OnboardingFragment.kt
  app/src/main/java/info/imdang/imdang/ui/login/onboarding/OnboardingPagerAdapter.kt
  app/src/main/java/info/imdang/imdang/ui/login/onboarding/OnboardingViewModel.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding.xml
  component/src/main/res/drawable/bg_onboarding_1.png
  component/src/main/res/drawable/bg_onboarding_2.png
  component/src/main/res/drawable/bg_onboarding_3.png
Labels: 리뷰 요청

#47 인사이트 목록 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/newinsight/NewInsightListActivity.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/newinsight/NewInsightViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/visitcomplex/VisitComplexInsightListActivity.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/visitcomplex/VisitComplexInsightListViewModel.kt
  app/src/main/res/layout/activity_new_insight_list.xml
  app/src/main/res/layout/activity_visit_complex_insight_list.xml
  app/src/main/res/layout/fragment_home_search.xml
  app/src/main/res/layout/item_insight_horizontal.xml
  app/src/main/res/layout/item_visit_complex_insight_apt.xml
  component/src/main/res/values/strings.xml
Labels: 리뷰 완료

#48 인사이트 작성 미구현 부분 구현
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/info/imdang/imdang/base/BaseViewModel.kt
  app/src/main/java/info/imdang/imdang/common/bindingadapter/ImageViewBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/common/ext/ContextExt.kt
  app/src/main/java/info/imdang/imdang/common/ext/EditTextExt.kt
  app/src/main/java/info/imdang/imdang/common/util/DateTimeUtils.kt
  app/src/main/java/info/imdang/imdang/model/address/KakaoAddressVo.kt
  app/src/main/java/info/imdang/imdang/ui/main/MainActivity.kt
  app/src/main/java/info/imdang/imdang/ui/write/WriteInsightActivity.kt
  app/src/main/java/info/imdang/imdang/ui/write/WriteInsightViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/write/address/KakaoAddressActivity.kt
  app/src/main/java/info/imdang/imdang/ui/write/bottomsheet/SelectImageBottomSheet.kt
  app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightBasicInfoFragment.kt
  app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightComplexEnvironmentFragment.kt
  app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightComplexFacilityFragment.kt
  app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightGoodNewsFragment.kt
  app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightInfraFragment.kt
  app/src/main/java/info/imdang/imdang/ui/write/review/WriteOverallReviewActivity.kt
  app/src/main/java/info/imdang/imdang/ui/write/summary/WriteInsightSummaryActivity.kt
  app/src/main/res/layout/activity_basic_information.xml
  app/src/main/res/layout/activity_write_insight.xml
  app/src/main/res/layout/activity_write_insight_summary.xml
  app/src/main/res/layout/activity_write_overall_review.xml
  app/src/main/res/layout/bottom_sheet_select_image.xml
  app/src/main/res/layout/dialog_common.xml
  app/src/main/res/layout/fragment_write_insight_basic_info.xml
  app/src/main/res/layout/fragment_write_insight_complex_environment.xml
  app/src/main/res/layout/fragment_write_insight_complex_facility.xml
  app/src/main/res/layout/fragment_write_insight_good_news.xml
  app/src/main/res/layout/fragment_write_insight_infra.xml
  app/src/main/res/xml/file_paths.xml
  component/src/main/res/drawable/bg_insight_summary_button.xml
  component/src/main/res/drawable/ic_polygon_down.xml
  component/src/main/res/drawable/ic_step.xml
  component/src/main/res/values/strings.xml
  data/src/main/java/info/imdang/data/constant/RemoteConstant.kt
  data/src/main/java/info/imdang/data/datasource/lcoal/AuthLocalDataSource.kt
  data/src/main/java/info/imdang/data/datasource/remote/InsightRemoteDataSource.kt
  data/src/main/java/info/imdang/data/di/NetworkModule.kt
  data/src/main/java/info/imdang/data/di/RepositoryModule.kt
  data/src/main/java/info/imdang/data/interceptor/TokenInterceptor.kt
  data/src/main/java/info/imdang/data/model/request/insight/WriteInsightRequest.kt
  data/src/main/java/info/imdang/data/model/response/insight/InsightIdResponse.kt
  data/src/main/java/info/imdang/data/repository/InsightRepositoryImpl.kt
  domain/src/main/java/info/imdang/domain/model/insight/InsightIdDto.kt
  domain/src/main/java/info/imdang/domain/model/insight/request/WriteInsightDto.kt
  domain/src/main/java/info/imdang/domain/repository/InsightRepository.kt
  domain/src/main/java/info/imdang/domain/usecase/insight/WriteInsightUseCase.kt
  gradle/libs.versions.toml
  local/src/main/java/info/imdang/local/datasource/AuthLocalDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/datasource/InsightRemoteDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/di/RemoteDataSourceModule.kt
  remote/src/main/java/info/imdang/remote/di/ServiceModule.kt
  remote/src/main/java/info/imdang/remote/service/InsightService.kt
Labels: 리뷰 요청

#50 인사이트 내역 없는 경우 UI 구현
  app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/storage/StorageFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/storage/StorageViewModel.kt
  app/src/main/res/layout/fragment_home_search.xml
  app/src/main/res/layout/fragment_storage.xml
  component/src/main/res/drawable/ic_ban.xml
  component/src/main/res/drawable/sr_dash_gray50_gray100_all8.xml
  component/src/main/res/drawable/sr_gray50_all100.xml
  component/src/main/res/values/strings.xml
Labels: 리뷰 요청, 리뷰 완료

#53 feat : 기본 정보 입력시 api 연결
  app/src/main/java/info/imdang/imdang/ui/join/BasicInformationActivity.kt
  app/src/main/java/info/imdang/imdang/ui/join/BasicInformationViewModel.kt
  data/src/main/java/info/imdang/data/datasource/remote/AuthRemoteDataSource.kt
  data/src/main/java/info/imdang/data/model/request/auth/OnboardingRequest.kt
  data/src/main/java/info/imdang/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/info/imdang/domain/model/auth/OnboardingDto.kt
  domain/src/main/java/info/imdang/domain/repository/AuthRepository.kt
  domain/src/main/java/info/imdang/domain/usecase/auth/OnboardingJoinUseCase.kt
  remote/src/main/java/info/imdang/remote/datasource/AuthRemoteDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/service/AuthService.kt
Labels: 리뷰 완료

#55 인사이트 신고하기 팝업 구현
  app/src/main/java/info/imdang/imdang/model/insight/InsightDetailVo.kt
  app/src/main/java/info/imdang/imdang/ui/common/CommonDialog.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailActivity.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailViewModel.kt
  app/src/main/res/layout/dialog_common.xml
  component/src/main/res/values/strings.xml
  component/src/main/res/values/text-styles.xml
Labels: 리뷰 완료

#58 인사이트 작성 API 연동
  app/src/main/java/info/imdang/imdang/common/bindingadapter/ImageViewBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/common/util/DateTimeUtils.kt
  app/src/main/java/info/imdang/imdang/common/util/SelectionManager.kt
  app/src/main/java/info/imdang/imdang/ui/write/WriteInsightActivity.kt
  app/src/main/java/info/imdang/imdang/ui/write/WriteInsightEvent.kt
  app/src/main/java/info/imdang/imdang/ui/write/WriteInsightViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightBasicInfoFragment.kt
  app/src/main/res/layout/activity_write_insight.xml
  app/src/main/res/layout/fragment_write_insight_basic_info.xml
  data/src/main/java/info/imdang/data/datasource/remote/InsightRemoteDataSource.kt
  data/src/main/java/info/imdang/data/model/request/insight/WriteInsightRequest.kt
  data/src/main/java/info/imdang/data/repository/InsightRepositoryImpl.kt
  domain/src/main/java/info/imdang/domain/model/insight/request/WriteInsightDto.kt
  domain/src/main/java/info/imdang/domain/repository/InsightRepository.kt
  domain/src/main/java/info/imdang/domain/usecase/insight/WriteInsightUseCase.kt
  remote/src/main/java/info/imdang/remote/datasource/InsightRemoteDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/service/InsightService.kt
Labels: 리뷰 완료

#61 인사이트 상세 api 연동
  app/src/main/java/info/imdang/imdang/common/bindingadapter/ChipBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/common/bindingadapter/ImageViewBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/common/bindingadapter/TextViewBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/model/auth/LoginVo.kt
  app/src/main/java/info/imdang/imdang/model/insight/InsightDetailItem.kt
  app/src/main/java/info/imdang/imdang/model/insight/InsightDetailState.kt
  app/src/main/java/info/imdang/imdang/model/insight/InsightDetailVo.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailActivity.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailAdapter.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/insight/bottomsheet/ExchangeItemsBottomSheet.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/history/HomeHistoryRequestedFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/newinsight/NewInsightListActivity.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/recommend/RecommendInsightsFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/visitcomplex/VisitComplexInsightListActivity.kt
  app/src/main/java/info/imdang/imdang/ui/main/storage/StorageFragment.kt
  app/src/main/java/info/imdang/imdang/ui/write/WriteInsightViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/write/fragment/WriteInsightBasicInfoFragment.kt
  app/src/main/res/layout/activity_insight_detail.xml
  app/src/main/res/layout/fragment_write_insight_basic_info.xml
  app/src/main/res/layout/item_insight_detail_apt_environment.xml
  app/src/main/res/layout/item_insight_detail_apt_facility.xml
  app/src/main/res/layout/item_insight_detail_basic_info.xml
  app/src/main/res/layout/item_insight_detail_good_news.xml
  app/src/main/res/layout/item_insight_detail_infra.xml
  component/src/main/res/values/strings.xml
  data/src/main/java/info/imdang/data/datasource/lcoal/AuthLocalDataSource.kt
  data/src/main/java/info/imdang/data/datasource/remote/InsightRemoteDataSource.kt
  data/src/main/java/info/imdang/data/model/response/auth/LoginResponse.kt
  data/src/main/java/info/imdang/data/model/response/insight/InsightDetailResponse.kt
  data/src/main/java/info/imdang/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/info/imdang/data/repository/InsightRepositoryImpl.kt
  domain/src/main/java/info/imdang/domain/model/auth/LoginDto.kt
  domain/src/main/java/info/imdang/domain/model/insight/InsightDetailDto.kt
  domain/src/main/java/info/imdang/domain/model/insight/request/WriteInsightDto.kt
  domain/src/main/java/info/imdang/domain/repository/AuthRepository.kt
  domain/src/main/java/info/imdang/domain/repository/InsightRepository.kt
  domain/src/main/java/info/imdang/domain/usecase/auth/GetMemberIdUseCase.kt
  domain/src/main/java/info/imdang/domain/usecase/auth/GoogleLoginUseCase.kt
  domain/src/main/java/info/imdang/domain/usecase/auth/KakaoLoginUseCase.kt
  domain/src/main/java/info/imdang/domain/usecase/auth/SaveMemberIdUseCase.kt
  domain/src/main/java/info/imdang/domain/usecase/insight/GetInsightDetailUseCase.kt
  local/src/main/java/info/imdang/local/constant/LocalConstant.kt
  local/src/main/java/info/imdang/local/datasource/AuthLocalDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/datasource/InsightRemoteDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/service/InsightService.kt
Labels: 리뷰 완료

#64 InsightDetailVo isReported 추가
  app/src/main/java/info/imdang/imdang/model/insight/InsightDetailVo.kt
Labels: 리뷰 완료

#67 서비스이용약관 화면 구현
  app/src/main/java/info/imdang/imdang/common/bindingadapter/ImageViewBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/ui/join/BasicInformationActivity.kt
  app/src/main/java/info/imdang/imdang/ui/join/BasicInformationViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/join/bottomsheet/ServiceTermBottomSheet.kt
  app/src/main/java/info/imdang/imdang/ui/login/onboarding/OnboardingViewModel.kt
  app/src/main/res/layout/bottom_sheet_service_term.xml
  app/src/main/res/layout/fragment_onboarding.xml
  component/src/main/res/values/strings.xml
Labels: 리뷰 완료

#73 쿠폰 조회, 교환 요청 API 연동
  app/src/main/java/info/imdang/imdang/model/insight/ExchangeRequestStatus.kt
  app/src/main/java/info/imdang/imdang/model/insight/InsightDetailVo.kt
  app/src/main/java/info/imdang/imdang/model/insight/InsightVo.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailActivity.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/main/MainActivity.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/HomeFragment.kt
  data/src/main/java/info/imdang/data/datasource/remote/CouponRemoteDataSource.kt
  data/src/main/java/info/imdang/data/datasource/remote/ExchangeRemoteDataSource.kt
  data/src/main/java/info/imdang/data/datasource/remote/MyInsightRemoteDataSource.kt
  data/src/main/java/info/imdang/data/di/RepositoryModule.kt
  data/src/main/java/info/imdang/data/model/exchange/ExchangeResponse.kt
  data/src/main/java/info/imdang/data/model/request/exchange/RequestExchangeRequest.kt
  data/src/main/java/info/imdang/data/model/response/insight/InsightResponse.kt
  data/src/main/java/info/imdang/data/repository/CouponRepositoryImpl.kt
  data/src/main/java/info/imdang/data/repository/ExchangeRepositoryImpl.kt
  data/src/main/java/info/imdang/data/repository/MyInsightRepositoryImpl.kt
  domain/src/main/java/info/imdang/domain/model/exchange/ExchangeDto.kt
  domain/src/main/java/info/imdang/domain/model/insight/InsightDto.kt
  domain/src/main/java/info/imdang/domain/repository/CouponRepository.kt
  domain/src/main/java/info/imdang/domain/repository/ExchangeRepository.kt
  domain/src/main/java/info/imdang/domain/repository/MyInsightRepository.kt
  domain/src/main/java/info/imdang/domain/usecase/coupon/GetCouponCountUseCase.kt
  domain/src/main/java/info/imdang/domain/usecase/exchange/RequestExchangeUseCase.kt
  domain/src/main/java/info/imdang/domain/usecase/myinsight/GetMyInsightsUseCase.kt
  remote/src/main/java/info/imdang/remote/datasource/CouponRemoteDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/datasource/ExchangeRemoteDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/datasource/MyInsightRemoteDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/di/RemoteDataSourceModule.kt
  remote/src/main/java/info/imdang/remote/di/ServiceModule.kt
  remote/src/main/java/info/imdang/remote/service/CouponService.kt
  remote/src/main/java/info/imdang/remote/service/ExchangeService.kt
  remote/src/main/java/info/imdang/remote/service/MyInsightService.kt
Labels: 리뷰 완료

#76 내 인사이트 목록 무한 스크롤 구현
  app/src/main/java/info/imdang/imdang/base/BasePagingDataAdapter.kt
  app/src/main/java/info/imdang/imdang/common/bindingadapter/RecyclerViewBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/ui/insight/InsightDetailViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/insight/bottomsheet/ExchangeItemsBottomSheet.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/search/HomeSearchViewModel.kt
  app/src/main/res/layout/bottom_sheet_exchange_items.xml
  app/src/main/res/layout/item_insight_detail_my_insight.xml
  data/src/main/java/info/imdang/data/repository/MyInsightRepositoryImpl.kt
  domain/src/main/java/info/imdang/domain/repository/MyInsightRepository.kt
  domain/src/main/java/info/imdang/domain/usecase/myinsight/GetMyInsightsWithPagingUseCase.kt
Labels: 리뷰 완료

#80 보관함 스크롤 시 상단 타이틀 변경
  app/src/main/java/info/imdang/imdang/ui/main/storage/StorageFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/storage/StorageViewModel.kt
  app/src/main/res/layout/fragment_storage.xml
Labels: 리뷰 완료

#82 인사이트 작성 qa
  app/src/main/java/info/imdang/imdang/ui/write/WriteInsightActivity.kt
  app/src/main/java/info/imdang/imdang/ui/write/WriteInsightEvent.kt
  app/src/main/java/info/imdang/imdang/ui/write/WriteInsightViewModel.kt
  component/src/main/java/info/imdang/component/Toast.kt
  component/src/main/res/drawable/bg_toast.xml
  component/src/main/res/layout/toast_common.xml
  component/src/main/res/values/colors.xml
Labels: 리뷰 완료

#84 알림 빈 화면 UI 구현
  app/src/main/java/info/imdang/imdang/model/notification/NotificationItem.kt
  app/src/main/java/info/imdang/imdang/model/notification/NotificationVo.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/notification/NotificationActivity.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/notification/NotificationItemDecoration.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/notification/NotificationViewModel.kt
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/item_notification_empty.xml
Labels: 리뷰 완료

#86 교환소 api 연동
  app/src/main/java/info/imdang/imdang/common/bindingadapter/ChipBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/common/bindingadapter/TextViewBindingAdapter.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/exchange/HomeExchangeAdapter.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/exchange/HomeExchangeFragment.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/exchange/HomeExchangeViewModel.kt
  app/src/main/java/info/imdang/imdang/ui/main/home/history/HomeHistoryRequestedFragment.kt
  app/src/main/res/layout/fragment_home_exchange.xml
  app/src/main/res/layout/fragment_home_history_requested.xml
  component/src/main/res/values/strings.xml
  data/src/main/java/info/imdang/data/datasource/remote/MyExchangeRemoteDataSource.kt
  data/src/main/java/info/imdang/data/di/RepositoryModule.kt
  data/src/main/java/info/imdang/data/repository/MyExchangeRepositoryImpl.kt
  domain/src/main/java/info/imdang/domain/model/common/MyExchangesParams.kt
  domain/src/main/java/info/imdang/domain/repository/MyExchangeRepository.kt
  domain/src/main/java/info/imdang/domain/usecase/myexchange/GetMyExchangeUseCase.kt
  domain/src/main/java/info/imdang/domain/usecase/myexchange/GetOthersExchangeUseCase.kt
  remote/src/main/java/info/imdang/remote/datasource/MyExchangeRemoteDataSourceImpl.kt
  remote/src/main/java/info/imdang/remote/di/RemoteDataSourceModule.kt
  remote/src/main/java/info/imdang/remote/di/ServiceModule.kt
  remote/src/main/java/info/imdang/remote/service/MyExchangeService.kt
Labels: 리뷰 완료

#88 온보딩, 기본정보입력, 가입완료 qa
  app/src/main/java/info/imdang/imdang/ui/join/JoinCompleteActivity.kt
  app/src/main/java/info/imdang/imdang/ui/login/onboarding/OnboardingActivity.kt
  app/src/main/java/info/imdang/imdang/ui/login/onboarding/OnboardingFragment.kt
  app/src/main/java/info/imdang/imdang/ui/login/onboarding/OnboardingViewModel.kt
  app/src/main/res/layout/activity_join_complete.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding.xml
Labels: 리뷰 요청
